### ISSUE TITLE
Randomly variable audio frequency

### ISSUE THREAD

**Issue by ppetru** [ppetru/morse-camp#14]
For each piece of text played, randomly pick a frequency from a range configured by the user.

**Comment by zoglmannk** [comment]
I have thought about implementing this in the near future. What range of frequencies should it cover? In the settings menu, the Frequency can be set from 200 to 1000Hz. RufzXP allows a max frequency of 1250Hz.

Do you think users should be able to limit the lower and upper bounds? I have some difficulty reliably copying below 300Hz. (Perhaps I just need more practice. hi hi)

**Comment by ppetru** [comment]
Configurable bounds sounds like a good idea, yes. I'd default them to something like 200 to 1200 and cap the configurable range to something sane (100 to 5000 maybe?).

**Comment by ppetru** [comment]
Implemented by @zoglmannk in #27.
