### ISSUE TITLE
Farnsworth spacing support

### ISSUE THREAD

**Issue by ppetru** [ppetru/morse-camp#2]
Somewhat controversial since extra spacing is not very useful for head copy skills. That said, multiple folks asked for it and it might help avoid scaring beginners away.

Farnsworth spacing is also better than lowering the speed too much, so once this is implemented we could raise the minimum speed to 18 WPM or so.

**Comment by zoglmannk** [comment]
If we added a Character Space Multiplier Slider and a Word Space Multiplier Slider, it would be straightforward to implement Farnsworth spacing. If we have to calculate the extra spacing based on an effective wpm slider, it would be more challenging to implement. From what I understand, there is no "standard" for Farnsworth timing.

If you are open to the easier implementation, I am open to doing the work. :)

**Comment by ppetru** [comment]
Agreed that the multipliers would be easier to implement, however using them would be somewhat confusing. The concept of a word speed vs character speed is easier to grasp and common, even if there's no actual standard...

**Comment by ppetru** [comment]
That said, check this out for an idea on how to calculate the space multipliers based on a given pair of WPM settings (normal & Farnsworth): https://github.com/scp93ch/morse-pro/blob/master/src/morse-pro-wpm.js

**Comment by zoglmannk** [comment]
True that would be more user-friendly. :)

**Comment by ppetru** [comment]
This is now implemented using the ARRL timing formulas at http://www.arrl.org/files/file/Technology/x9004008.pdf.

**Comment by zoglmannk** [comment]
Awesome! I was going to work on that after the Manual Repeat Feature.
