### ISSUE TITLE
Manual Repeat Option

### ISSUE THREAD

**Issue by zoglmannk** [ppetru/morse-camp#22]
In the Read Trainer Settings, the user should be able to toggle between Manual and Automatic repeats. If they select Manual repeats, the Delay Before Repeat and Max Repeat Sliders should be disabled or dynamically disappear.

It is important to preserve the user experience and limit UI/UX clutter in the Reader Trainer. I recommend that the button be placed next to the SHOW button.

(I have had a couple of users request an option for a manual repeat.)

![repeat](https://user-images.githubusercontent.com/65922/48271256-90c91e80-e401-11e8-94e6-27a65ac3eea1.jpg)

**Comment by ppetru** [comment]
Agreed, this would be nice to have and something multiple users requested. It's high up on my list, just didn't have the time yet.

**Comment by ppetru** [comment]
Implemented in #25
