### ISSUE TITLE
Disabling `Automatically Repeat` is not saved between application/page starts

### ISSUE THREAD

**Issue by krasoffski** [ppetru/morse-camp#45]
**Steps for reproduce**

1. Open configuration
2. Disable `Automatically Repeat`
3. Refresh page or re-launch web-application
4. Open configuration 

**Actual result:**
Disabled `Automatically Repeat` is not persisted in local storage.

**Expected result:**
Disabled `Automatically Repeat` is persisted to local storage between restarts.

**Comment by ppetru** [comment]
Thanks for reporting this. It should be fixed now.
